### ISSUE TITLE
redsocks2 http流量转发失败怎么办

### ISSUE THREAD

**Issue by brightsm** [semigodking/redsocks#62]
内网  一台代理服务器  ip = 10.0.0.10;  port = 8080;支持http   https代理服务
现在想访问外网80  443端口的数据流量走代理，其他端口的流量走正常外网

路由器网卡：
LAN 192.168.24.1
WAN  192.168.23.126

//resocks2,conf配置
base {
  log_debug = off; 
  log_info = off;
  daemon = on;
  redirector= iptables;
}

redsocks {
 local_ip = 127.0.0.1;
 local_port = 11111;
 ip = 10.0.0.10;
 port = 8080;
 type = http-relay;
 timeout = 12;
 autoproxy = 1;
}

redsocks {
 local_ip = 127.0.0.1;
 local_port = 11112;
 ip = 10.0.0.10;
 port = 8080;
 type = http-connect;
 timeout = 12;
 autoproxy = 1;
}

redsocks {
 local_ip = 127.0.0.1;
 local_port = 11113;
 interface = eth0;
 type = direct;
 timeout = 20;
}

autoproxy {
 no_quick_check_seconds = 0;
}

ipcache {
    // Configure IP cache
    cache_size = 4;   // Maximum number of IP's in 1K. 
    stale_time = 900; // Seconds to stale an IP in cache since it is added
                      // into cahce.
                      // Set it to 0 to disable cache stale.
    port_check = 1;   // Whether to distinguish port number in address
    cache_file = "/tmp/ipcache.txt"; // File used to store blocked IP's in cache.
    autosave_interval = 3600; // Interval for saving ip cache into file.
                              // Set it to 0 to disable autosave.
    // When autosave_interval and stale_time are both 0, IP cache behaves like
    // a static blacklist. 
}

iptables脚本:

#!/bin/ash
redsocks2 -c  ./redsocks2.conf

iptables -t nat -N RSHTTPS
iptables -t nat -A RSHTTPS -o lo -j RETURN
iptables -t nat -A RSHTTPS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTPS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTPS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTPS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A RSHTTPS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A RSHTTPS -d 172.17.0.0/12 -j RETURN
iptables -t nat -A RSHTTPS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A RSHTTPS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A RSHTTPS -d 240.0.0.0/4 -j RETURN
iptables -t nat -A RSHTTPS -p tcp -j REDIRECT --to-port 11112
iptables -t nat -I PREROUTING -p tcp --dport 443 -j RSHTTPS
#iptables -t nat -I PREROUTING -p udp -j RSHTTPS

iptables -t nat -N RSHTTP
iptables -t nat -A RSHTTP -o lo -j RETURN
iptables -t nat -A RSHTTP -d 0.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTP -d 10.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTP -d 127.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTP -d 169.254.0.0/16 -j RETURN
iptables -t nat -A RSHTTP -d 172.16.0.0/12 -j RETURN
iptables -t nat -A RSHTTP -d 172.17.0.0/12 -j RETURN
iptables -t nat -A RSHTTP -d 192.168.0.0/16 -j RETURN
iptables -t nat -A RSHTTP -d 224.0.0.0/4 -j RETURN
iptables -t nat -A RSHTTP -d 240.0.0.0/4 -j RETURN
iptables -t nat -A RSHTTP -p tcp -j REDIRECT --to-port 11111
iptables -t nat -I PREROUTING -p tcp --dport 80 -j RSHTTP

iptables -t nat -N RSDIRECT
iptables -t nat -A RSDIRECT -p tcp -j REDIRECT --to-port 11113
iptables -t nat -I PREROUTING -p tcp -d 192.168.23.126 -j RSDIRECT

**Comment by semigodking** [comment]
local_ip不能使用127.0.0.1，应该使用lan的ip, 即192.168.24.1

2016年12月24日 21:30，"brightsm" <notifications@github.com>写道：

内网 一台代理服务器 ip = 10.0.0.10; port = 8080;支持http https代理服务
现在想访问外网80 443端口的数据流量走代理，其他端口的流量走正常外网

路由器网卡：
LAN 192.168.24.1
WAN 192.168.23.126

//resocks2,conf配置
base {
log_debug = off;
log_info = off;
daemon = on;
redirector= iptables;
}

redsocks {
local_ip = 127.0.0.1;
local_port = 11111;
ip = 10.0.0.10;
port = 8080;
type = http-relay;
timeout = 12;
autoproxy = 1;
}

redsocks {
local_ip = 127.0.0.1;
local_port = 11112;
ip = 10.0.0.10;
port = 8080;
type = http-connect;
timeout = 12;
autoproxy = 1;
}

redsocks {
local_ip = 127.0.0.1;
local_port = 11113;
interface = eth0;
type = direct;
timeout = 20;
}

autoproxy {
no_quick_check_seconds = 0;
}

ipcache {
// Configure IP cache
cache_size = 4; // Maximum number of IP's in 1K.
stale_time = 900; // Seconds to stale an IP in cache since it is added
// into cahce.
// Set it to 0 to disable cache stale.
port_check = 1; // Whether to distinguish port number in address
cache_file = "/tmp/ipcache.txt"; // File used to store blocked IP's in
cache.
autosave_interval = 3600; // Interval for saving ip cache into file.
// Set it to 0 to disable autosave.
// When autosave_interval and stale_time are both 0, IP cache behaves like
// a static blacklist.
}

iptables脚本:

#!/bin/ash
redsocks2 -c ./redsocks2.conf

iptables -t nat -N RSHTTPS
iptables -t nat -A RSHTTPS -o lo -j RETURN
iptables -t nat -A RSHTTPS -d 0.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTPS -d 10.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTPS -d 127.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTPS -d 169.254.0.0/16 -j RETURN
iptables -t nat -A RSHTTPS -d 172.16.0.0/12 -j RETURN
iptables -t nat -A RSHTTPS -d 172.17.0.0/12 -j RETURN
iptables -t nat -A RSHTTPS -d 192.168.0.0/16 -j RETURN
iptables -t nat -A RSHTTPS -d 224.0.0.0/4 -j RETURN
iptables -t nat -A RSHTTPS -d 240.0.0.0/4 -j RETURN
iptables -t nat -A RSHTTPS -p tcp -j REDIRECT --to-port 11112
iptables -t nat -I PREROUTING -p tcp --dport 443 -j RSHTTPS
#iptables -t nat -I PREROUTING -p udp -j RSHTTPS

iptables -t nat -N RSHTTP
iptables -t nat -A RSHTTP -o lo -j RETURN
iptables -t nat -A RSHTTP -d 0.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTP -d 10.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTP -d 127.0.0.0/8 -j RETURN
iptables -t nat -A RSHTTP -d 169.254.0.0/16 -j RETURN
iptables -t nat -A RSHTTP -d 172.16.0.0/12 -j RETURN
iptables -t nat -A RSHTTP -d 172.17.0.0/12 -j RETURN
iptables -t nat -A RSHTTP -d 192.168.0.0/16 -j RETURN
iptables -t nat -A RSHTTP -d 224.0.0.0/4 -j RETURN
iptables -t nat -A RSHTTP -d 240.0.0.0/4 -j RETURN
iptables -t nat -A RSHTTP -p tcp -j REDIRECT --to-port 11111
iptables -t nat -I PREROUTING -p tcp --dport 80 -j RSHTTP

iptables -t nat -N RSDIRECT
iptables -t nat -A RSDIRECT -p tcp -j REDIRECT --to-port 11113
iptables -t nat -I PREROUTING -p tcp -d 192.168.23.126 -j RSDIRECT

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/semigodking/redsocks/issues/62>, or mute the thread

**Comment by brightsm** [comment]
base {
  log_debug = off; 
  log_info = off;
  daemon = on;
  redirector= iptables;
}



redsocks {
 local_ip = 192.168.24.1;//内网网关IP地址
 local_port = 11112;
 ip = 10.0.0.10;//远程代理服务器ip地址
 port = 8080;////远程代理服务器服务端口
 type = http-connect;
 timeout = 25;
 autoproxy = 0;
}

redsocks {
 local_ip = 192.168.24.1;
 local_port = 11111;
 ip = 10.0.0.10;
 port = 8080;
 type = http-relay;
 timeout = 25;
 autoproxy = 0;
}

redsocks {
 local_ip = 192.168.24.1;
 local_port = 11113;
 interface = br-lan;//内网网关所在的网络接口
 type = direct;
 timeout = 20;
}


autoproxy {
 no_quick_check_seconds = 0;
}

ipcache {
    // Configure IP cache
    cache_size = 4;   // Maximum number of IP's in 1K. 
    stale_time = 900; // Seconds to stale an IP in cache since it is added
                      // into cahce.
                      // Set it to 0 to disable cache stale.
    port_check = 1;   // Whether to distinguish port number in address
    cache_file = "/tmp/ipcache.txt"; // File used to store blocked IP's in cache.
    autosave_interval = 3600; // Interval for saving ip cache into file.
                              // Set it to 0 to disable autosave.
    // When autosave_interval and stale_time are both 0, IP cache behaves like
    // a static blacklist. 
}

这样改一下就好了，然后再运行iptables添加链规则的脚本。

**Comment by semigodking** [comment]
很好，你自己解决了。
