### ISSUE TITLE
有没有可能像PC平台SS客户端一样支持在服务器端域名解析呢？

### ISSUE THREAD

**Issue by yanggis** [semigodking/redsocks#68]
现在好像android版的SS客户端，路由器版本的SS客户端，还是redsocks2都是本地进行域名解析，解析出来IP之后直接发到远程服务器，远程服务器再傻傻地根据客户端指定的IP上获取数据，这就有很大的弊端，一是不能保证连的服务器是SS服务器端最快的，最近的，其次就是不能抵抗DNS干扰。
如果redsocks2作为SS的客户端，发给SS服务器的是一个域名，SS服务器收到域名就地解析，就可以获取当地最快的服务器，还可以避免DNS污染，现在的PC平台的SS客户端就是这个思路，所以PC上就不需要防止DNS污染，也可以保证数据请求速度。
redsocks2能在这方面做改进吗？

**Comment by semigodking** [comment]
Pc端是怎么玩的？设置socks5代理？

2017年4月12日 16:47，"X.K. YANG" <notifications@github.com>写道：

**Comment by yanggis** [comment]
PC端就是安装这个shadowsocks for windows的软件：
https://github.com/shadowsocks/shadowsocks-windows/releases

**Comment by semigodking** [comment]
关键是安装后具体怎么使用？

2017年4月12日 20:33，"X.K. YANG" <notifications@github.com>写道：

**Comment by yanggis** [comment]
这个你安装一下可以自己看看，很简单。
另外redsocks2里面的http relay，把http中继给远程的http代理服务器，比如squid，也是把域名发送给远程的squid服务器，squid服务器收到域名之后再在本地解析对应的IP，再去请求数据的。

**Comment by semigodking** [comment]
如果按你说的这个方法去做的话，就要尝试解应用层数据，发现是http的才有可能。但也会慢很多，每个连接都要到远端查dns

2017年4月12日 21:05，"X.K. YANG" <notifications@github.com>写道：

这个你安装一下可以自己看看，很简单。
另外redsocks2里面的http relay，把http中继给远程的http代理服务器，比如squid，也是把域名发送给远程的squid服务器，
squid服务器收到域名之后再在本地解析对应的IP，再去请求数据的。

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/semigodking/redsocks/issues/68#issuecomment-293569257>,
or mute the thread

**Comment by yanggis** [comment]
能不能把包的解析稍微调整一下，比如现在发包是host是IP的，换成域名发过去，让服务器收到之后在本地来解析。

**Comment by yanggis** [comment]
因为现在shadowsocks的PC端把域名的包发过去，SS服务器收到之后就可以解析出来，说明服务器端已经具备这个能力了。

**Comment by semigodking** [comment]
这不可能的.因为redsocks透明代理机制是基于IP的, 依赖于iptables. 除非深层解析应用层协议，否则没办法知道连接所对应的host。

2017年4月12日 22:01，"X.K. YANG" <notifications@github.com>写道：

**Comment by yanggis** [comment]
哦，好吧……

**Comment by shellus** [comment]
@yanggis 虽然redsocks5不能够做到远程解析DNS.
但是你可以在路由器上运行一个ss-tunnel来建立一个DNS Server。
然后通过iptables转发所有目标端口为53端口的UDP包到127.0.0.1:53来实现远程的DNS解析。
