### ISSUE TITLE
Maintain an addr->name cache for SOCKS and HTTP-CONNECT requests

### ISSUE THREAD

**Issue by RoganDawes** [semigodking/redsocks#69]
It is useful to be able to use the hostname in the HTTP CONNECT request (or SOCKS connect request) rather than the IP address. The code implemented here: https://github.com/rogandawes/redsocks

achieves this for http-connect requests.

I'd appreciate feedback on the implementation, if possible.

**Comment by semigodking** [comment]
Suggestion: do not hardcode EOL as \r\n. As sometimes, you may want to feed
the pipe with a text file.

Have you verified your solution on other platforms, like FreeBSD,  openwrt?

2017年5月3日 18:11，"RoganDawes" <notifications@github.com>写道：

It is useful to be able to use the hostname in the HTTP CONNECT request (or
SOCKS connect request) rather than the IP address. The code implemented
here: https://github.com/rogandawes/redsocks

achieves this for http-connect requests.

I'd appreciate feedback on the implementation, if possible.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/semigodking/redsocks/issues/69>, or mute the thread

**Comment by RoganDawes** [comment]
Hi,

I didn't think that I *had* hardcoded EOL at all. And I have tried cat'ing a file to the fifo, with the expected results.

I guess I'm asking more for comments from a "Is this patch in line with the existing code style?", etc perspective. I am no kind of C programmer at all, so I am quite expecting to have screwed something up badly!

I *do* intend for this code to be run on an OpenWRT router, but as yet, I have not tested it in this capacity.

**Comment by semigodking** [comment]
For hardcoded EOL, see lines below.
char *ptr = buf, *line, *lf = "\r\n";


line = strtok_r(ptr, lf, &ptr);

I will take closer look at your code later.

2017年5月3日 21:33，"RoganDawes" <notifications@github.com>写道：

Hi,

I didn't think that I *had* hardcoded EOL at all. And I have tried cat'ing
a file to the fifo, with the expected results.

I guess I'm asking more for comments from a "Is this patch in line with the
existing code style?", etc perspective. I am no kind of C programmer at
all, so I am quite expecting to have screwed something up badly!

I *do* intend for this code to be run on an OpenWRT router, but as yet, I
have not tested it in this capacity.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/semigodking/redsocks/issues/69#issuecomment-298911852>,
or mute the thread

**Comment by RoganDawes** [comment]
The *lf is used by strtok, which considers any of the characters to be a delimiter. I could reverse them in the string, and should get the same results from strtok, I believe. At any rate, the files that I have been passing to this code have not had DOS-style CR/LF line endings.

**Comment by semigodking** [comment]
You are right. i misunderstood the delimiter parm of strtok.

2017年5月4日 15:34，"RoganDawes" <notifications@github.com>写道：

The *lf is used by strtok, which considers any of the characters to be a
delimiter. I could reverse them in the string, and should get the same
results from strtok, I believe. At any rate, the files that I have been
passing to this code have not had DOS-style CR/LF line endings.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/semigodking/redsocks/issues/69#issuecomment-299115737>,
or mute the thread

**Comment by semigodking** [comment]
Finally got time to review your code changes. From code style perspective, your code looks okay. If I were you, I would not introduce hash table as IP:hostname pair storage. I would use tree instead so that I could use tsearch/tfind functions just like redudp does. The benefit is that no additional code introduced so that to keep your code change clean. The efficiency should not be a problem with tree search.

**Comment by RoganDawes** [comment]
Ah, ok. Will have a look at that, no problem.

I was actually rethinking my approach of creating a whole new subsystem, though, and thought it might make sense to add the "reverse lookup" functionality into the redsocks subsystem itself. That would eliminate the problem of passing a reference to a specific instance of the rdns subsystem to an instance of the redsocks subsystem.

Seems cleaner, somehow!

**Comment by gilcu3** [comment]
Did you finish implementing this @RoganDawes , or it was meged at some point to redsocks2 @semigodking . This is a quite useful feature as some proxies in some dark environments block access to ip and only allow hostnames int HTTP CONNECT requests.

**Comment by RoganDawes** [comment]
@gilcu3 As far as I am aware, it was not merged. I have not reworked it as simply part of the redsocks subsystem yet, either, unfortunately. It *does* work as posted, so if you want to try it, you should find it functional, if not as clean as one might like.

**Comment by cheng1li** [comment]
Agree with @gilcu3 , some web sites block ip access, we can only access those sites with domain name. i.e. https://www.google.com 
@RoganDawes 's code may work, but I think a better implement is to extract the hostname from tcp payload, instead of sending dns request.

**Comment by RoganDawes** [comment]
In https://github.com/SensePost/Mallet, I obtain the hostname from things like the SNI fields in the SSL negotiation. However, not all clients support SNI yet, and consequently, it is still necessary to be able to map an IP address to a DNS name at some point. I have this as an optional mutation step in Mallet, but it should be manually done where necessary.
Having redsocks automatically do that mapping would be nicer.
